# cmake/_Dependencies.cmake is generated by `mulle-sde`. Edits will be lost.
# Last update: 2018-03-13 21:17:04
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

# there are no linkable dependencies in the sourcetree
