# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
# Last update: 2018-03-13 21:17:03
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
) 

set( PUBLIC_HEADERS
src/mulle_c11.h
) 

