# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
# Last update: 2018-03-13 21:17:03
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

# source generation turned off by MULLE_SDE_CMAKE_SOURCES_FILE
